# ///-----------------------------------------///
# /// @file    gamma_test.mac
# /// @brief   Macro for test run with gamma 
# /// @author  Goro Yabu
# /// @date    2020/02/19
# ///-----------------------------------------///

##################################################
### Verbose
##################################################

/control/verbose 1
/run/verbose 1

##################################################
## Geometry
##################################################

/wstrip/geom/setLengthOf  worldSize      15    cm

/wstrip/geom/setLengthOf  detectorSize   32.0  mm
/wstrip/geom/setLengthOf  detectorGap    4     mm

#/wstrip/geom/setPositionOf detectorCenter 0. 0. 0. mm

/wstrip/geom/addDetectorLayer Si 500. um
/wstrip/geom/addDetectorLayer Si 500. um
/wstrip/geom/addDetectorLayer CdTe 750 um
/wstrip/geom/addDetectorLayer CdTe 750 um
/wstrip/geom/addDetectorLayer CdTe 750 um

/run/initialize

##################################################
### PrimaryGenerator
##################################################

## Choose 1 Option
#/wstrip/prim/useParticleGun
/wstrip/prim/useGPS

##################################################
### ParticleGun 
##################################################

/gun/particle  gamma
/gun/energy    511.0 keV
/gun/position  0. 0. 1. mm
/gun/direction 0. 0. -1.

##################################################
### GeneralParticleSource
##################################################

### Point Source
/gps/particle gamma
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/centre 0. 0. 41. mm
/gps/pos/halfx 0.5 mm
/gps/pos/halfy 0.5 mm
/gps/ang/type iso
/gps/ang/maxtheta 90 deg
/gps/ene/type Mono
/gps/ene/mono 511.0 keV
#/gps/ene/min 511.0 keV
#/gps/ene/max 511.0 keV

### Beam
# /gps/particle gamma
# /gps/pos/type Plane
# /gps/pos/shape Circle
# /gps/pos/centre 0. 0. 50. mm
# /gps/pos/radius	25 mm
# #/gps/pos/halfx 25 mm
# #/gps/pos/halfy 25 mm
# /gps/ang/type iso
# /gps/ang/maxtheta 0 deg
# /gps/ene/type Mono
# /gps/ene/mono 511.0 keV

##################################################
### Analysis
##################################################

/analysis/setFileName sim
/analysis/h1/set 0  1000 0. 1000. keV 

##################################################
### Run
##################################################

/run/setCut 100 um
/run/beamOn 10000

#------------------------------------------------